#!/bin/bash

yum update -y
yum install -y httpd jq

region=$(curl --silent http://169.254.169.254/latest/dynamic/instance-identity/document | jq -r .region)
instanceId=$(curl http://169.254.169.254/latest/meta-data/instance-id)
echo "<h1>Hello World from <b>$instanceId</b> from region <b>$region</b></h1>" > /var/www/html/index.html

systemctl start httpd
systemctl enable httpd
