#!/bin/bash

yum update -y
yum install -y httpd jq

region=$(curl --silent http://169.254.169.254/latest/dynamic/instance-identity/document | jq -r .region)
az=$(curl --silent http://169.254.169.254/latest/dynamic/instance-identity/document  | jq -r  .availabilityZone)
instanceId=$(curl http://169.254.169.254/latest/meta-data/instance-id)
echo "<h1>Hello World from <b>$instanceId</b> <br> in region <b>$region</b> <br>in zone: <b>$az</b> </h1>" > /var/www/html/index.html

systemctl start httpd
systemctl enable httpd
